tasks 4-6
ZeRori4/IDP pull request #1
Opened 2024-01-28 23:09 UTC by ZeRori4

2024-01-30 15:22 UTC, inna-tuzhikova requested changes

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +data = dict(user_1=dict(a=10, b=70),
на верхнем уровне тестовые данные не нужны. их нужно создавать внутри тестов

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +    expected_result = "70: user_1"
строчка равняется `"70: user_1"`. все остальные строки просто никуда не идут. также есть ошибка в основном методе, которая прикрывает это

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +def test_b_equal_1_report():
тут, скорее, уместнее название `test_same_b_for_all_users`

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +    expected_result = None
тут ожидаемый результат пустая строка, раз уж основная функция возвращает строку

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +def test_report_all_b_different():
я бы назвала `test_unique_b_for_each_user`

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +    expected_result = "70: user_1"
проверь, чему в дебагере равняется `expected_result`. это касается всех тестов

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +def test_base_report():
`test_non_unique_b`

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task4.py
> +def test_report_more_dict_in_users():
`test_extra_fields_in_data`

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +        #print(f"{func.__name__}({args}) = {result:.3f}")
все закомменченные строки нужно удалять, если в них нет супер потребности

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +def sin_printer(x):
я бы эти функции для теста определяла в самих тестах, а не на верхнем уровне

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +x = 1
на глобальном уровне тестовые данные не нужны. пусть они будут свои для каждого теста

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +def test_name_func_sin():
здорово, что добавил тест на сохранение оригинального имени)

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +def test_name_func_cos():
один и тот же по сути тест: test_name_func_sin и test_name_func_cos. лучше убрать дубли и придумать новый тест по смыслу

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +    expected_result = 22  # cos_printer(1) = 0.540
по сути это дубль теста test_sin_printer_1. просто сравнение строки

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +def pretty_printer(func):
все ок)

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +def test_name_func_cos():
можно 5 тестов организовать так: 1й - сохранение имени, 2-5 - отдельные прогоны с разными случаями (когда 0 после точки, допустим).

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task6.py
> +def straightened_list(original_list):
обычно эту функцию называют flatten, а так всё ок

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task6.py
> +def test_list_recursion():
я бы назвала `test_nested_list_level_1` - многоуровневый список уровня 1

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task6.py
> +def test_level_3_list_recursion():
я бы назвала `test_nested_list_level_3` - многоуровневый список уровня 3

2024-01-30 15:22 UTC, inna-tuzhikova commented on tasks 4-6/task6.py
> +        print("test_nested_list: ok")
название не совпадает с названием теста. поправь здесь и везде, когда будешь всё проверять и править имена функций

2024-02-06 10:56 UTC, inna-tuzhikova requested changes

2024-02-06 10:56 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +    actual_result = len('{:.3f}'.format(
а зачем тебе форматировать с '{:.3f}' результат функции? ты как бы даёшь ему подсказку. оставь просто len(cos_printer(0).split('.')[-1])

2024-02-06 10:56 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +    actual_result = len('{:.3f}'.format(
даже если там выдаст два знака после зпт, то этот тест скажет, что всё ок

2024-02-06 10:56 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +    expected_result = '{:.3f}'.format(float(cos_printer(1).split('= ')[-1]))
напиши сразу строку, которая должна получиться. expected ты всегда прописываешь сам, а не сравниваешь выхлоп функции с выхлопом функции

2024-02-06 10:56 UTC, inna-tuzhikova commented on tasks 4-6/task5.py
> +    actual_result = sin_printer(x).endswith("000")
`.endswith(".000")`

2024-02-07 06:55 UTC, inna-tuzhikova approved these changes

2024-03-04 14:19 UTC, gvrlv requested changes

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/10/onboarding 10.py
> +        <name>Канал:</name>
для чего :?

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/10/onboarding 10.py
> +if user_function == "с фигурами":
лучше засунуть в функцию

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/11/onboarding 11.py
> +from func import *
плохой подход, лучше не использовать импорт через *

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/11/resources/func.py
> +class Func:
нужно дать более понятное название

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/11/onboarding 11.py
> +alert(result)
ответ должен возвращаться в ошибке интерфейса через raise

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/12/onboarding 12.py
> +if user_function == "с фигурами":
для чего это тут? Нужно делать скриншоты через ShotSaver и учитывать фигуры

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/13/onboarding 13.py
> +ss.save(
нужно учитывать фигуры

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/14/onboarding 14.py
> +# -*- coding: utf-8 -*-
имелось ввиду использование функции host.send_mail_from_account

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/5/onboarding 5.py
> +result = [(x[0], x[1]) for x in objects_list(TYPE_OBJ)]
можно было бы просто проитерироваться по дереву объектов

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/6/onboarding 6.py
> +for camera in guid_camers:
засунь в функцию

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/6/onboarding 6.py
> +raise Exception(result)
зачем raise?

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/7/onboarding 7.py
> +def name_ip_device():
лучше назвать set_new_ip_device_names

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/7/onboarding 7.py
> +    for x in host.objects_list("IP Device"):
почему ты не итерируешься по дереву объектов сервера?

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/9/onboarding 9.py
> +full_path = shots_path + "/" + name_file
os.path.join

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/9/onboarding 9.py
> +for camera in guid_camers:
засунь в функцию

2024-03-04 14:19 UTC, gvrlv commented on onboarding 1-35/8/onboarding 8.py
> +content = os.listdir("C:/DSSL/")
нужно содержимое script_path

2024-06-13 23:07 UTC, merged